name: plantaera
description: A mobile application that can help you in your gardening journey.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  email_validator: ^2.1.17
  shared_preferences: ^2.2.2
  dotted_border: ^2.1.0
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  path: ^1.8.3
  image_picker: ^1.0.4
  image: ^4.1.3
  rxdart: ^0.27.7
  tflite_v2: ^1.0.0
  intl: ^0.18.1
  flutter_local_notifications: ^16.1.0
  android_alarm_manager_plus: ^3.0.3
  flutter_timezone: ^1.0.8
  objectbox: ^2.3.1
  objectbox_flutter_libs: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  firebase_storage: ^11.4.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
  build_runner: ^2.0.0
  objectbox_generator: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/plantaera-logo.png"
  min_sdk_android: 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/admin-plant-icon.png
    - assets/admin-plant-icon-darken.png
    - assets/plant-icon.png
    - assets/plant-icon-darken.png
    - assets/plantaera-logo-removebg.png
    - assets/plantaera-logo.png
    - assets/admin-banner.jpg
    - assets/gardening-guide-banner.jpg
    - assets/identification-disease-bg.jpg
    - assets/identification-plant-bg.jpg
    - assets/plant_model.tflite
    - assets/plant_labels.txt
    - assets/disease_model.tflite
    - assets/disease_labels.txt

